opt_in_rules:
  - all
disabled_rules:
  - anyobject_protocol
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - inert_defer
  - no_grouping_extension
  - no_magic_numbers
  - prefer_nimble
  - required_deinit
  - vertical_whitespace_between_cases
  - unowned_variable_capture
  - unused_capture_list

identifier_name:
  excluded:
    - id
    - d4
    - d6
    - d8

large_tuple: 3
function_body_length: 60
type_body_length: 400